sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
services:
  - docker
env:
  global:
    # Do not prompt for user input when using any SDK methods.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: tests
      script:
        - docker build --target builder -t kliment1986/client-test:latest ./frontend/.
        - docker run -e CI=true kliment1986/client-test:latest npm run test

    - stage: tests
      script:
        - docker build -t kliment1986/api-test:latest ./backend/.
        - docker run --env-file ./backend/tst.env kliment1986/api-test:latest python manage.py test

    - stage: gcloud deploy
      script:
        - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        # Add gcloud to $PATH
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file service-account.json
        - gcloud config set project bustling-bot-327005
        - gcloud config set compute/zone europe-north1-a
        - gcloud container clusters get-credentials k8s-exmapmle-cluster
      deploy:
        provider: script
        script: bash ./deploy/deploy.sh
      on:
        branch: main
