apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  - name: client
    image: klimentru1986/kubernatestodo-client
    ports:
    - containerPort: 80